from bs4 import BeautifulSoup
from get_problem import *
import os

def get_problem(problem_number):
	script_dir = os.path.dirname(__file__)
	with open(os.path.join(script_dir, f"p{problem_number}.html")) as input_html_file:
		input_html = input_html_file.read()
	actual = parse_html(input_html)
	with open(os.path.join(script_dir, f"../p{problem_number}.md")) as expected_file:
		expected = expected_file.read()
	assert actual == expected

#def test_get_problem_108():
#	get_problem(108)

#def test_get_problem_800():
#	get_problem(800)

def test_parse_paragraph_strong():
	input_html = r"This period is called the <strong>Pisano period</strong> for $n$, often shortened to $\pi(n)$."
	paragraph = BeautifulSoup(input_html, 'html.parser')
	actual = parse_paragraph(paragraph)
	expected = r"This period is called the **Pisano period** for $n$, often shortened to $\pi(n)$."
	assert actual == expected

def test_parse_paragraph_newlines():
	input_html = r"""For every positive integer $n$ the Fibonacci sequence modulo 
$n$ is periodic. The period depends on the value of $n$."""
	paragraph = BeautifulSoup(input_html, 'html.parser')
	actual = parse_paragraph(paragraph)
	expected = r"For every positive integer $n$ the Fibonacci sequence modulo $n$ is periodic. The period depends on the value of $n$."
	assert actual == expected

def test_parse_paragraph_break():
	input_html = r"""An integer of the form $p^q q^p$ with prime numbers $p \neq q$ is called a <dfn>hybrid-integer</dfn>.<br>
For example, $800 = 2^5 5^2$ is a hybrid-integer."""
	paragraph = BeautifulSoup(input_html, 'html.parser')
	actual = parse_paragraph(paragraph)
	expected = r"""An integer of the form $p^q q^p$ with prime numbers $p \neq q$ is called a _hybrid-integer_.
For example, $800 = 2^5 5^2$ is a hybrid-integer."""
	assert actual == expected

def test_parse_paragraph_double_dollar_sign():
	input_html = r"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$"""
	paragraph = BeautifulSoup(input_html, 'html.parser')
	actual = parse_paragraph(paragraph)
	expected = r"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
```math
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots
```"""
	assert actual == expected